
# --------------------------------------------------
# Bible Books
#
# Use the SAME list as import_bible.py.
# Never guess book names from filenames.
# --------------------------------------------------

BOOKS = [
    ("genesis", "Genesis", "Old Testament"),
    ("exodus", "Exodus", "Old Testament"),
    ("leviticus", "Leviticus", "Old Testament"),
    ("numbers", "Numbers", "Old Testament"),
    ("deuteronomy", "Deuteronomy", "Old Testament"),
    ("joshua", "Joshua", "Old Testament"),
    ("judges", "Judges", "Old Testament"),
    ("ruth", "Ruth", "Old Testament"),
    ("1samuel", "1 Samuel", "Old Testament"),
    ("2samuel", "2 Samuel", "Old Testament"),
    ("1kings", "1 Kings", "Old Testament"),
    ("2kings", "2 Kings", "Old Testament"),
    ("1chronicles", "1 Chronicles", "Old Testament"),
    ("2chronicles", "2 Chronicles", "Old Testament"),
    ("ezra", "Ezra", "Old Testament"),
    ("nehemiah", "Nehemiah", "Old Testament"),
    ("esther", "Esther", "Old Testament"),
    ("job", "Job", "Old Testament"),
    ("psalms", "Psalms", "Old Testament"),
    ("proverbs", "Proverbs", "Old Testament"),
    ("ecclesiastes", "Ecclesiastes", "Old Testament"),
    ("songofsolomon", "Song of Solomon", "Old Testament"),
    ("isaiah", "Isaiah", "Old Testament"),
    ("jeremiah", "Jeremiah", "Old Testament"),
    ("lamentations", "Lamentations", "Old Testament"),
    ("ezekiel", "Ezekiel", "Old Testament"),
    ("daniel", "Daniel", "Old Testament"),
    ("hosea", "Hosea", "Old Testament"),
    ("joel", "Joel", "Old Testament"),
    ("amos", "Amos", "Old Testament"),
    ("obadiah", "Obadiah", "Old Testament"),
    ("jonah", "Jonah", "Old Testament"),
    ("micah", "Micah", "Old Testament"),
    ("nahum", "Nahum", "Old Testament"),
    ("habakkuk", "Habakkuk", "Old Testament"),
    ("zephaniah", "Zephaniah", "Old Testament"),
    ("haggai", "Haggai", "Old Testament"),
    ("zechariah", "Zechariah", "Old Testament"),
    ("malachi", "Malachi", "Old Testament"),

    ("matthew", "Matthew", "New Testament"),
    ("mark", "Mark", "New Testament"),
    ("luke", "Luke", "New Testament"),
    ("john", "John", "New Testament"),
    ("acts", "Acts", "New Testament"),
    ("romans", "Romans", "New Testament"),
    ("1corinthians", "1 Corinthians", "New Testament"),
    ("2corinthians", "2 Corinthians", "New Testament"),
    ("galatians", "Galatians", "New Testament"),
    ("ephesians", "Ephesians", "New Testament"),
    ("philippians", "Philippians", "New Testament"),
    ("colossians", "Colossians", "New Testament"),
    ("1thessalonians", "1 Thessalonians", "New Testament"),
    ("2thessalonians", "2 Thessalonians", "New Testament"),
    ("1timothy", "1 Timothy", "New Testament"),
    ("2timothy", "2 Timothy", "New Testament"),
    ("titus", "Titus", "New Testament"),
    ("philemon", "Philemon", "New Testament"),
    ("hebrews", "Hebrews", "New Testament"),
    ("james", "James", "New Testament"),
    ("1peter", "1 Peter", "New Testament"),
    ("2peter", "2 Peter", "New Testament"),
    ("1john", "1 John", "New Testament"),
    ("2john", "2 John", "New Testament"),
    ("3john", "3 John", "New Testament"),
    ("jude", "Jude", "New Testament"),
    ("revelation", "Revelation", "New Testament"),
]
